# Generated by Django 2.0.4 on 2018-04-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('sub_item', models.CharField(max_length=64)),
                ('price_small', models.IntegerField()),
                ('price_large', models.IntegerField()),
            ],
        ),
    ]
