# Generated by Django 2.0.4 on 2018-04-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price_large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price_small',
            field=models.FloatField(),
        ),
    ]
