# Generated by Django 2.0.4 on 2018-04-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item',
        ),
    ]
