# Generated by Django 2.0.4 on 2018-04-18 04:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='first',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price_large',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price_small',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sub_item',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_waiting', to='orders.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
